package Pantallas.vistas.dialogos;

import dtos.AsistenciaDTO;
import java.awt.Color;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author Brian Sandoval - 262741
 */
public class DlgMensaje extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DlgMensaje.class.getName());

    /**
     * Creates new form DlgMensaje
     */
    public DlgMensaje(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void mostrarExito(String titulo, String mensaje) {
        setTitle(titulo);
        PanContenedor.setBackground(new Color(230, 255, 230));

        jLabel1.setText(
                "<html><div style='text-align:center;'>"
                + "<h1 style='color:#1B8A3D;'>✔ " + titulo + "</h1>"
                + "<br>"
                + "<span style='font-size:16px;'>"
                + mensaje
                + "</span>"
                + "</div></html>"
        );

        jButton1.setBackground(new Color(27, 138, 61));
        pack();
    }

    public void mostrarError(String titulo, String mensaje) {
        setTitle(titulo);
        PanContenedor.setBackground(new Color(255, 235, 235));

        jLabel1.setText(
                "<html><div style='text-align:center;'>"
                + "<h1 style='color:#C62828;'>✖ " + titulo + "</h1>"
                + "<br>"
                + "<span style='font-size:16px;'>"
                + mensaje
                + "</span>"
                + "</div></html>"
        );

        jButton1.setBackground(new Color(198, 40, 40));
        pack();
    }

    /**
     * Variante de mostrarError específicamente diseñada para informar que un
     * boleto ya fue utilizado, mostrando la fecha y hora del registro.
     */
    public void mostrarErrorBoletoUsado(String titulo, String mensaje, AsistenciaDTO asistencia) {
        setTitle(titulo);
        PanContenedor.setBackground(new Color(255, 235, 235));

        // Formateamos la fecha para que sea fácil de leer (ej. 19/05/2026 15:30)
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
        String fechaFormateada = (asistencia.getFechaHoraRegistro() != null) ? asistencia.getFechaHoraRegistro().format(formatter) : "Fecha desconocida";

        jLabel1.setText(
                "<html><div style='text-align:center;'>"
                + "<h1 style='color:#C62828;'>✖ " + titulo + "</h1>"
                + "<br>"
                + "<span style='font-size:16px;'>" + mensaje + "</span>"
                + "<br><br>"
                + "<span style='font-size:14px; color:#555555;'>"
                + "<b>Fecha de uso:</b> " + fechaFormateada
                + "</span>"
                + "</div></html>"
        );

        jButton1.setBackground(new Color(198, 40, 40));
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanContenedor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PanContenedor.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mensaje");

        jButton1.setBackground(new java.awt.Color(31, 92, 204));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanContenedorLayout = new javax.swing.GroupLayout(PanContenedor);
        PanContenedor.setLayout(PanContenedorLayout);
        PanContenedorLayout.setHorizontalGroup(
            PanContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanContenedorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
            .addGroup(PanContenedorLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        PanContenedorLayout.setVerticalGroup(
            PanContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanContenedorLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanContenedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
