/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;

import Controlador.interfaz.ICoordinadorAplicacion;
import dtos.RegistroUsuarioDTO;
import dtos.UsuarioDTO;
import excepciones.CoordinadorException;
import javax.swing.JOptionPane;
import utilerias.BotonUtileria;

/**
 *
 * @author Aaron Burciaga - 262788
 * @author Brian Sandoval - 262741
 * @author Dayanara Peralta - 262695
 * @author María Valdez - 262775
 */
public class FrmRegistrarse extends javax.swing.JFrame {

    private ICoordinadorAplicacion coordinador;

    public FrmRegistrarse() {
        initComponents();

    }

    /**
     * Creates new form frmInicioSesion
     *
     * @param coordinador
     */
    public FrmRegistrarse(ICoordinadorAplicacion coordinador) {
        this.coordinador = coordinador;
        initComponents();
        BotonUtileria.estilizarBoton(btnRegistrarse);
    }

    private void mostrarMensaje(String message) {
        JOptionPane.showMessageDialog(null, message, "Advertencia", JOptionPane.WARNING_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        iniciaSesion = new javax.swing.JLabel();
        txtContrasenia = new javax.swing.JPasswordField();
        lblContrasenia = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        jPanelAzul = new javax.swing.JPanel();
        textiniciaSesion = new javax.swing.JLabel();
        txtConfirmacionContrasenia = new javax.swing.JPasswordField();
        lblContraseniaConfirmacion = new javax.swing.JLabel();
        btnRegistrarse = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtApellidoP = new javax.swing.JTextField();
        lblApellidoP = new javax.swing.JLabel();
        txtApellidoM = new javax.swing.JTextField();
        lblApellidoM = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(248, 248, 248));
        jPanel1.setPreferredSize(new java.awt.Dimension(845, 465));

        iniciaSesion.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        iniciaSesion.setForeground(new java.awt.Color(0, 0, 0));
        iniciaSesion.setText("<html>¿Ya tienes cuenta? <font color=\"blue\"><u>Iniciar Sesión</u></font></html>");
        iniciaSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iniciaSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iniciaSesionMouseClicked(evt);
            }
        });

        txtContrasenia.setBackground(new java.awt.Color(234, 230, 230));
        txtContrasenia.setForeground(java.awt.Color.black);

        lblContrasenia.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblContrasenia.setForeground(new java.awt.Color(0, 0, 0));
        lblContrasenia.setText("Contraseña");

        txtCorreo.setBackground(new java.awt.Color(234, 230, 230));
        txtCorreo.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtCorreo.setForeground(java.awt.Color.black);
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });

        lblCorreo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(0, 0, 0));
        lblCorreo.setText("Correo");

        jPanelAzul.setBackground(new java.awt.Color(31, 92, 204));
        jPanelAzul.setPreferredSize(new java.awt.Dimension(597, 50));

        textiniciaSesion.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        textiniciaSesion.setForeground(new java.awt.Color(255, 255, 255));
        textiniciaSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textiniciaSesion.setText("Registrarse");

        javax.swing.GroupLayout jPanelAzulLayout = new javax.swing.GroupLayout(jPanelAzul);
        jPanelAzul.setLayout(jPanelAzulLayout);
        jPanelAzulLayout.setHorizontalGroup(
            jPanelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textiniciaSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelAzulLayout.setVerticalGroup(
            jPanelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAzulLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textiniciaSesion)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        txtConfirmacionContrasenia.setBackground(new java.awt.Color(234, 230, 230));
        txtConfirmacionContrasenia.setForeground(java.awt.Color.black);

        lblContraseniaConfirmacion.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblContraseniaConfirmacion.setForeground(new java.awt.Color(0, 0, 0));
        lblContraseniaConfirmacion.setText("Confirmar contraseña");

        btnRegistrarse.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnRegistrarse.setText("Registrarse");
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseActionPerformed(evt);
            }
        });

        txtNombre.setBackground(new java.awt.Color(234, 230, 230));
        txtNombre.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtNombre.setForeground(java.awt.Color.black);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        lblNombre.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre.setText("Nombre(s)");

        txtApellidoP.setBackground(new java.awt.Color(234, 230, 230));
        txtApellidoP.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtApellidoP.setForeground(java.awt.Color.black);
        txtApellidoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoPActionPerformed(evt);
            }
        });

        lblApellidoP.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblApellidoP.setForeground(new java.awt.Color(0, 0, 0));
        lblApellidoP.setText("Apellido Paterno");

        txtApellidoM.setBackground(new java.awt.Color(234, 230, 230));
        txtApellidoM.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtApellidoM.setForeground(java.awt.Color.black);
        txtApellidoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoMActionPerformed(evt);
            }
        });

        lblApellidoM.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblApellidoM.setForeground(new java.awt.Color(0, 0, 0));
        lblApellidoM.setText("Apellido Materno");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAzul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iniciaSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblApellidoM)
                            .addComponent(lblApellidoP)
                            .addComponent(lblNombre)
                            .addComponent(lblContraseniaConfirmacion)
                            .addComponent(lblContrasenia)
                            .addComponent(lblCorreo)
                            .addComponent(txtContrasenia)
                            .addComponent(txtCorreo)
                            .addComponent(txtConfirmacionContrasenia, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                            .addComponent(txtNombre)
                            .addComponent(txtApellidoP)
                            .addComponent(txtApellidoM))))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblApellidoP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblApellidoM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(lblCorreo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblContrasenia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblContraseniaConfirmacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtConfirmacionContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(iniciaSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciaSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciaSesionMouseClicked
        coordinador.mostrarInicioSesion();
    }//GEN-LAST:event_iniciaSesionMouseClicked

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
        String pass = String.valueOf(txtContrasenia.getPassword());
        String confirmPass = String.valueOf(txtConfirmacionContrasenia.getPassword());

        if (!pass.equals(confirmPass)) {
            JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String regex = "^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$";
        String regexCorreo = "^[\\w.-]+@[\\w.-]+\\.[a-zA-Z]{2,}$";

        if (!txtNombre.getText().trim().matches(regex)) {
            JOptionPane.showMessageDialog(null, "El nombre solo debe contener letras", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!txtApellidoP.getText().trim().matches(regex)) {
            JOptionPane.showMessageDialog(null, "El apellido paterno solo debe contener letras", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String apellidoM = txtApellidoM.getText().trim();
        if (!apellidoM.isEmpty() && !apellidoM.matches(regex)) {
            JOptionPane.showMessageDialog(null, "El apellido materno solo debe contener letras", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String correo = txtCorreo.getText().trim();
        if (!correo.matches(regexCorreo)) {
            JOptionPane.showMessageDialog(null, "Correo electrónico no válido", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        RegistroUsuarioDTO usuario = new RegistroUsuarioDTO(txtNombre.getText().trim(), txtApellidoP.getText().trim(), apellidoM.isEmpty() ? null : apellidoM, correo, pass);

        UsuarioDTO usuarioGuardado;
        try {
            usuarioGuardado = coordinador.guardarUsuario(usuario);

            if (usuarioGuardado != null) {
                JOptionPane.showMessageDialog(null, "Usuario registrado correctamente", "Registro exitoso", JOptionPane.INFORMATION_MESSAGE);
                txtNombre.setText("");
                txtApellidoP.setText("");
                txtApellidoM.setText("");
                txtContrasenia.setText("");
                txtConfirmacionContrasenia.setText("");
                txtCorreo.setText("");
                coordinador.mostrarInicioSesion();
            }
        } catch (CoordinadorException ex) {
            mostrarMensaje(ex.getMessage());
        }
    }//GEN-LAST:event_btnRegistrarseActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtApellidoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoPActionPerformed

    private void txtApellidoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoMActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JLabel iniciaSesion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAzul;
    private javax.swing.JLabel lblApellidoM;
    private javax.swing.JLabel lblApellidoP;
    private javax.swing.JLabel lblContrasenia;
    private javax.swing.JLabel lblContraseniaConfirmacion;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel textiniciaSesion;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JPasswordField txtConfirmacionContrasenia;
    private javax.swing.JPasswordField txtContrasenia;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
