package Pantallas.vistas;

import Controlador.interfaz.ICoordinadorAplicacion;
import dtos.EventoDTO;
import excepciones.CoordinadorException;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author Brian Sandoval - 262741
 *
 */
public class PnlCheckIn extends javax.swing.JPanel {

    private final ICoordinadorAplicacion coordinador;
    private EventoDTO evento;

    /**
     * Creates new form PnlCheckIn
     *
     * @param coordinador
     * @param evento
     */
    public PnlCheckIn(ICoordinadorAplicacion coordinador, EventoDTO evento) {
        initComponents();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");

        this.coordinador = coordinador;
        this.evento = evento;

        lblNombreEvento.setText(evento.getNombreEvento());
        lblFechaEvento.setText(evento.getFechaHora().format(formatter));
        lblUbicacionEvento.setText(evento.getUbicacion().getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImagen = new javax.swing.JLabel();
        lblNombreEvento = new javax.swing.JLabel();
        lblFechaEvento = new javax.swing.JLabel();
        lblUbicacionEvento = new javax.swing.JLabel();
        btnAsistencias = new javax.swing.JButton();
        btnCheckIn = new javax.swing.JButton();

        setBackground(new java.awt.Color(221, 212, 212));

        lblImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagen.setText("imagen");

        lblNombreEvento.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblNombreEvento.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreEvento.setText("nombre");

        lblFechaEvento.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblFechaEvento.setForeground(new java.awt.Color(0, 0, 0));
        lblFechaEvento.setText("fecha");

        lblUbicacionEvento.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblUbicacionEvento.setForeground(new java.awt.Color(0, 0, 0));
        lblUbicacionEvento.setText("ubicacion");

        btnAsistencias.setBackground(new java.awt.Color(31, 92, 204));
        btnAsistencias.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnAsistencias.setForeground(new java.awt.Color(0, 0, 0));
        btnAsistencias.setText("Asistencias");
        btnAsistencias.setBorderPainted(false);
        btnAsistencias.setOpaque(true);
        btnAsistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsistenciasActionPerformed(evt);
            }
        });

        btnCheckIn.setBackground(new java.awt.Color(233, 134, 20));
        btnCheckIn.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnCheckIn.setForeground(new java.awt.Color(0, 0, 0));
        btnCheckIn.setText("Check in");
        btnCheckIn.setBorderPainted(false);
        btnCheckIn.setOpaque(true);
        btnCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAsistencias)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCheckIn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreEvento)
                            .addComponent(lblFechaEvento)
                            .addComponent(lblUbicacionEvento))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 23, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblNombreEvento)
                        .addGap(18, 18, 18)
                        .addComponent(lblFechaEvento)
                        .addGap(18, 18, 18)
                        .addComponent(lblUbicacionEvento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAsistencias)
                            .addComponent(btnCheckIn))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckInActionPerformed
        try {
            coordinador.mostrarCamara(evento);
        } catch (CoordinadorException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnCheckInActionPerformed

    private void btnAsistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsistenciasActionPerformed
        try {
            coordinador.mostrarAsistencias(evento);
        } catch (CoordinadorException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAsistenciasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsistencias;
    private javax.swing.JButton btnCheckIn;
    private javax.swing.JLabel lblFechaEvento;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblNombreEvento;
    private javax.swing.JLabel lblUbicacionEvento;
    // End of variables declaration//GEN-END:variables
}
