
package Pantallas.vistas;

import Controlador.coordinador.CoordinadorAplicacion;

/**
 *
 * @author Kaleb
 */
public class PnlConsultarMenu extends javax.swing.JPanel {

    private final CoordinadorAplicacion coordinador;

    public PnlConsultarMenu(CoordinadorAplicacion coordinador) {
        initComponents();

        this.coordinador = coordinador;
        utilerias.BotonUtileria.estilizarBoton(btnEventosPasados);
        utilerias.BotonUtileria.estilizarBoton(btnEventosProximos);
        utilerias.BotonUtileria.estilizarBoton(btnEventosCancelados);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEventosPasados = new javax.swing.JButton();
        btnEventosProximos = new javax.swing.JButton();
        btnEventosCancelados = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        btnEventosPasados.setBackground(new java.awt.Color(31, 92, 204));
        btnEventosPasados.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnEventosPasados.setForeground(new java.awt.Color(255, 255, 255));
        btnEventosPasados.setText("Eventos Pasados");
        btnEventosPasados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEventosPasadosActionPerformed(evt);
            }
        });

        btnEventosProximos.setBackground(new java.awt.Color(31, 92, 204));
        btnEventosProximos.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnEventosProximos.setForeground(new java.awt.Color(255, 255, 255));
        btnEventosProximos.setText("Eventos Próximos");
        btnEventosProximos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEventosProximosActionPerformed(evt);
            }
        });

        btnEventosCancelados.setBackground(new java.awt.Color(31, 92, 204));
        btnEventosCancelados.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnEventosCancelados.setForeground(new java.awt.Color(255, 255, 255));
        btnEventosCancelados.setText("Eventos Cancelados");
        btnEventosCancelados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEventosCanceladosActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel2.setText("Consultar Reservaciones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEventosCancelados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEventosProximos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEventosPasados, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(jLabel2)))
                .addContainerGap(381, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(btnEventosPasados, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnEventosProximos, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnEventosCancelados, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEventosPasadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEventosPasadosActionPerformed
        coordinador.mostrarConsultar("Pasados");
    }//GEN-LAST:event_btnEventosPasadosActionPerformed

    private void btnEventosProximosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEventosProximosActionPerformed
        coordinador.mostrarConsultar("Proximos");
    }//GEN-LAST:event_btnEventosProximosActionPerformed

    private void btnEventosCanceladosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEventosCanceladosActionPerformed
        coordinador.mostrarConsultar("Cancelados");
    }//GEN-LAST:event_btnEventosCanceladosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEventosCancelados;
    private javax.swing.JButton btnEventosPasados;
    private javax.swing.JButton btnEventosProximos;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
